version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: jamstockanalytics-webhook
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - WEBHOOK_PORT=3000
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - MAIN_APP_URL=${MAIN_APP_URL}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - webhook-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  webhook-monitor:
    image: curlimages/curl:latest
    container_name: webhook-monitor
    depends_on:
      - webhook
    command: >
      sh -c "
        echo 'Starting webhook monitoring...' &&
        while true; do
          curl -f http://webhook:3000/health || echo 'Health check failed';
          sleep 30;
        done
      "
    networks:
      - webhook-network
    restart: unless-stopped

networks:
  webhook-network:
    driver: bridge

volumes:
  webhook-logs:
    driver: local
