version: '3.8'

services:
  jamstockanalytics:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./static:/usr/share/nginx/html/static:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./web-config.html:/usr/share/nginx/html/web-config.html:ro
      - ./web-preview.html:/usr/share/nginx/html/web-preview.html:ro
      - ./logo.png:/usr/share/nginx/html/logo.png:ro
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico:ro
