# Production Docker Compose Configuration
services:
  jamstockanalytics:
    build: .
    container_name: jamstockanalytics-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NGINX_PORT=80
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - prod-network
    labels:
      - "com.jamstockanalytics.service=web"
      - "com.jamstockanalytics.version=1.0.0"
      - "traefik.enable=true"
      - "traefik.http.routers.jamstockanalytics.rule=Host(`jamstockanalytics-oss.github.io`)"

volumes:
  nginx-logs:
    driver: local

networks:
  prod-network:
    driver: bridge
    name: jamstockanalytics-prod-network
