-- Fixed data population script for JamStockAnalytics
-- This script correctly matches the database schema

BEGIN;

-- Create market_prices table if it doesn't exist (not in main schema)
CREATE TABLE IF NOT EXISTS public.market_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker text NOT NULL,
  price numeric,
  currency text,
  source text,
  retrieved_at timestamptz,
  market_cap bigint,
  created_at timestamptz DEFAULT now()
);

-- Upsert into company_tickers (using correct column name 'company_name' not 'name')
INSERT INTO public.company_tickers (ticker, company_name, exchange, sector, market_cap, is_active)
VALUES
('NCBFG', 'NCB Financial Group Limited', 'JSE', 'Financial Services', 45000000000, true),
('SGJ', 'Scotia Group Jamaica Limited', 'JSE', 'Financial Services', 32000000000, true),
('JMMB', 'JMMB Group Limited', 'JSE', 'Financial Services', 28000000000, true),
('BGL', 'Barita Investments Limited', 'JSE', 'Financial Services', 15000000000, true),
('SGL', 'Sagicor Group Jamaica Limited', 'JSE', 'Financial Services', 38000000000, true),
('JPS', 'Jamaica Public Service Company Limited', 'JSE', 'Utilities', 25000000000, true),
('WCO', 'Wisynco Group Limited', 'JSE', 'Manufacturing', 18000000000, true),
('KREMI', 'Kremi Limited', 'JSE', 'Manufacturing', 8000000000, true),
('PJAM', 'PanJam Investment Limited', 'JSE', 'Investment', 12000000000, true),
('JSE', 'Jamaica Stock Exchange Limited', 'Junior', 'Financial Services', 5000000000, true),
('CAC', 'CAC 2000 Limited', 'Junior', 'Technology', 2000000000, true),
('DCOVE', 'Dolphin Cove Limited', 'Junior', 'Tourism', 3000000000, true),
('KEX', 'Knutsford Express Services Limited', 'Junior', 'Transportation', 1500000000, true),
('PULSE', 'Pulse Investments Limited', 'Junior', 'Entertainment', 1000000000, true)
ON CONFLICT (ticker) DO UPDATE SET 
  company_name = EXCLUDED.company_name, 
  exchange = EXCLUDED.exchange, 
  sector = EXCLUDED.sector, 
  market_cap = EXCLUDED.market_cap, 
  is_active = EXCLUDED.is_active;

-- Upsert into market_prices
INSERT INTO public.market_prices (ticker, price, currency, source, retrieved_at, market_cap)
VALUES
('NCBFG', 85.50, 'JMD', 'exchange', NOW(), 45000000000),
('SGJ', 42.75, 'JMD', 'exchange', NOW(), 32000000000),
('JMMB', 38.20, 'JMD', 'exchange', NOW(), 28000000000),
('BGL', 25.80, 'JMD', 'exchange', NOW(), 15000000000),
('SGL', 55.25, 'JMD', 'exchange', NOW(), 38000000000),
('JPS', 12.40, 'JMD', 'exchange', NOW(), 25000000000),
('WCO', 18.75, 'JMD', 'exchange', NOW(), 18000000000),
('KREMI', 8.90, 'JMD', 'exchange', NOW(), 8000000000),
('PJAM', 15.60, 'JMD', 'exchange', NOW(), 12000000000),
('JSE', 2.45, 'JMD', 'exchange', NOW(), 5000000000)
ON CONFLICT (ticker) DO UPDATE SET 
  price = EXCLUDED.price, 
  market_cap = EXCLUDED.market_cap, 
  retrieved_at = EXCLUDED.retrieved_at;

COMMIT;

-- Verification counts
SELECT 'Company Tickers' as table_name, COUNT(*) as record_count FROM public.company_tickers
UNION ALL
SELECT 'Market Prices', COUNT(*) FROM public.market_prices;