name: Docker Build and Security Scan

on:
  push:
    branches: [ master, main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'JamStockAnalytics/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'JamStockAnalytics/**'
  workflow_dispatch:

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t jamstockanalytics:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'jamstockanalytics:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  docker-compose-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test docker-compose
        run: |
          echo "🧪 Testing docker-compose configuration..."
          docker compose config
          echo "✅ docker-compose.yml is valid"

      - name: Build with docker-compose
        run: |
          echo "🔨 Building with docker-compose..."
          docker compose build
          echo "✅ Build completed successfully"
