name: Automated Build with Enhanced Validation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build with Enhanced Validation
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run comprehensive validation
        run: npm run validate-all
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPO_PUBLIC_DEEPSEEK_API_KEY: ${{ secrets.EXPO_PUBLIC_DEEPSEEK_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          DEEPSEEK_TEMPERATURE: ${{ secrets.DEEPSEEK_TEMPERATURE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
          WINDOW_MS: ${{ secrets.WINDOW_MS }}
          MAX_MESSAGES: ${{ secrets.MAX_MESSAGES }}
          CLEANUP_DAYS: ${{ secrets.CLEANUP_DAYS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Setup database
        run: npm run setup-database
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPO_PUBLIC_DEEPSEEK_API_KEY: ${{ secrets.EXPO_PUBLIC_DEEPSEEK_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          DEEPSEEK_TEMPERATURE: ${{ secrets.DEEPSEEK_TEMPERATURE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
          WINDOW_MS: ${{ secrets.WINDOW_MS }}
          MAX_MESSAGES: ${{ secrets.MAX_MESSAGES }}
          CLEANUP_DAYS: ${{ secrets.CLEANUP_DAYS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Seed database
        run: npm run seed-database
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPO_PUBLIC_DEEPSEEK_API_KEY: ${{ secrets.EXPO_PUBLIC_DEEPSEEK_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          DEEPSEEK_TEMPERATURE: ${{ secrets.DEEPSEEK_TEMPERATURE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
          WINDOW_MS: ${{ secrets.WINDOW_MS }}
          MAX_MESSAGES: ${{ secrets.MAX_MESSAGES }}
          CLEANUP_DAYS: ${{ secrets.CLEANUP_DAYS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build application
        run: npm run build:auto
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPO_PUBLIC_DEEPSEEK_API_KEY: ${{ secrets.EXPO_PUBLIC_DEEPSEEK_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          DEEPSEEK_TEMPERATURE: ${{ secrets.DEEPSEEK_TEMPERATURE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
          WINDOW_MS: ${{ secrets.WINDOW_MS }}
          MAX_MESSAGES: ${{ secrets.MAX_MESSAGES }}
          CLEANUP_DAYS: ${{ secrets.CLEANUP_DAYS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Deploy application
        run: npm run deploy:auto
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          EXPO_PUBLIC_DEEPSEEK_API_KEY: ${{ secrets.EXPO_PUBLIC_DEEPSEEK_API_KEY }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          DEEPSEEK_TEMPERATURE: ${{ secrets.DEEPSEEK_TEMPERATURE }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          PORT: ${{ secrets.PORT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          RATE_LIMIT: ${{ secrets.RATE_LIMIT }}
          WINDOW_MS: ${{ secrets.WINDOW_MS }}
          MAX_MESSAGES: ${{ secrets.MAX_MESSAGES }}
          CLEANUP_DAYS: ${{ secrets.CLEANUP_DAYS }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Generate build report
        run: |
          echo "🚀 Enhanced Build Report" >> $GITHUB_STEP_SUMMARY
          echo "=========================" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Comprehensive validation completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ Database setup completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ Database seeding completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ Application build completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "✅ Application deployment completed successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🎉 Build and deployment completed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "🔒 All security validations passed" >> $GITHUB_STEP_SUMMARY
          echo "⚡ Enhanced validation system working perfectly" >> $GITHUB_STEP_SUMMARY
